#!/usr/bin/env bash
# One-shot local environment bootstrap.
#
# Usage:   ./scripts/setup.sh
# Idempotent — safe to re-run (existing .env is preserved unless you
# answer 'y' to overwrite).

set -euo pipefail

cd "$(dirname "$0")/.."

# --------------------------------------------------------- python version
# ccxt 4.5+ uses syntax that requires Python 3.10. Pick the newest
# interpreter on PATH that satisfies that.
find_python() {
  local candidates=(python3.13 python3.12 python3.11 python3.10 python3)
  for cmd in "${candidates[@]}"; do
    if command -v "$cmd" >/dev/null 2>&1; then
      local ver
      ver=$("$cmd" -c 'import sys; print("%d.%d"%sys.version_info[:2])' 2>/dev/null || echo "0.0")
      local major minor
      IFS=. read -r major minor <<< "$ver"
      if [ "${major:-0}" -ge 3 ] && [ "${minor:-0}" -ge 10 ]; then
        echo "$cmd"
        return 0
      fi
    fi
  done
  return 1
}

if ! PY=$(find_python); then
  cat <<'MSG' >&2
!! no Python >= 3.10 found on PATH.
   ccxt 4.5+ cannot run on Python 3.9 or older.

   macOS:     brew install python@3.11
   Ubuntu:    sudo apt install python3.11 python3.11-venv
   then re-run ./scripts/setup.sh
MSG
  exit 1
fi
echo "▶ using $PY ($("$PY" -V))"

# ------------------------------------------------------------- venv + pip
if [ ! -d .venv ]; then
  echo "▶ creating .venv with $PY"
  "$PY" -m venv .venv
else
  # re-verify the existing venv is on a supported python
  existing_ver=$(.venv/bin/python -c 'import sys; print("%d.%d"%sys.version_info[:2])' 2>/dev/null || echo "0.0")
  existing_major=${existing_ver%%.*}
  existing_minor=${existing_ver##*.}
  if [ "${existing_major:-0}" -lt 3 ] || [ "${existing_minor:-0}" -lt 10 ]; then
    echo "▶ existing .venv uses Python $existing_ver — recreating with $PY"
    rm -rf .venv
    "$PY" -m venv .venv
  fi
fi

# shellcheck disable=SC1091
source .venv/bin/activate

echo "▶ upgrading pip"
pip install --upgrade pip >/dev/null

echo "▶ installing requirements"
pip install -r requirements.txt

# ----------------------------------------------------------- .env helpers
ENV_FILE=".env"

prompt_secret() {         # prompt_secret VAR_NAME "human prompt"
  local var="$1" label="$2" value=""
  while [ -z "$value" ]; do
    read -r -s -p "  $label: " value
    echo
    if [ -z "$value" ]; then
      echo "    (empty — please enter a value)"
    fi
  done
  printf -v "$var" '%s' "$value"
}

prompt_optional() {       # prompt_optional VAR_NAME "human prompt" default
  local var="$1" label="$2" def="${3:-}" value=""
  if [ -n "$def" ]; then
    read -r -p "  $label [$def]: " value
  else
    read -r -p "  $label (optional, leave blank to skip): " value
  fi
  [ -z "$value" ] && value="$def"
  printf -v "$var" '%s' "$value"
}

prompt_yn() {             # prompt_yn VAR_NAME "human prompt" default(Y/n)
  local var="$1" label="$2" def="${3:-Y}" ans=""
  read -r -p "  $label [$def]: " ans
  ans="${ans:-$def}"
  case "$ans" in
    y|Y|yes|YES) printf -v "$var" 'true' ;;
    *)           printf -v "$var" 'false' ;;
  esac
}

# --------------------------------------------------------- interactive env
write_env=1
if [ -f "$ENV_FILE" ]; then
  echo
  echo "▶ .env already exists"
  read -r -p "  overwrite it with new answers? [y/N]: " ans
  case "${ans:-N}" in
    y|Y|yes|YES) write_env=1 ;;
    *)           write_env=0 ;;
  esac
fi

if [ "$write_env" = "1" ]; then
  echo
  echo "▶ entering Gate.io + optional secrets (keys are hidden as you type)"
  prompt_secret  GATE_API_KEY    "Gate.io API key"
  prompt_secret  GATE_API_SECRET "Gate.io API secret"
  prompt_optional CRYPTOPANIC_TOKEN "CryptoPanic token"
  prompt_optional CLAUDE_CLI        "claude CLI binary" "claude"
  prompt_yn      DRY_RUN_BOOL    "start in DRY_RUN mode (simulated orders, recommended)" "Y"
  prompt_optional LOG_LEVEL         "log level (DEBUG/INFO/WARNING)" "INFO"

  umask 077   # .env should be user-only
  cat > "$ENV_FILE" <<ENV
# generated by scripts/setup.sh — edit freely
GATE_API_KEY=$GATE_API_KEY
GATE_API_SECRET=$GATE_API_SECRET
CRYPTOPANIC_TOKEN=$CRYPTOPANIC_TOKEN
CLAUDE_CLI=$CLAUDE_CLI
DRY_RUN=$DRY_RUN_BOOL
LOG_LEVEL=$LOG_LEVEL
ENV
  chmod 600 "$ENV_FILE"
  echo "  ✓ wrote $ENV_FILE (permissions 600)"
fi

# ---------------------------------------------------------- claude CLI check
echo
echo "▶ checking claude CLI"
if ! command -v claude >/dev/null 2>&1; then
  cat <<'MSG'
!! claude CLI not found on PATH.
   Install it:
     npm i -g @anthropic-ai/claude-code
   Then log in:
     claude login
   (a Claude Max subscription is required to call opus via -p)
MSG
else
  claude --version || true
fi

# ----------------------------------------------------------- next steps
echo
echo "✅ setup complete."
cat <<'DONE'

Next steps:
  1) source .venv/bin/activate
  2) python scripts/doctor.py        # preflight checks
  3) ./scripts/test.sh               # run the offline unit tests
  4) python -m runner.main           # start the bot (DRY_RUN until you disable it)
DONE
